# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ZGTextProj' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZGTextProj
  pod 'AFNetworking', '~> 3.0'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'SDWebImage', '4.3.0'
  pod 'YYText'
  pod 'WebViewJavascriptBridge'

  target 'ZGTextProjTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZGTextProjUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
